<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInitdfbdffb07027e0ffeae8e38d7fd30cf6
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('SmartAutoUploadImages\Vendor_Prefixed\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \SmartAutoUploadImages\Vendor_Prefixed\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInitdfbdffb07027e0ffeae8e38d7fd30cf6', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \SmartAutoUploadImages\Vendor_Prefixed\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInitdfbdffb07027e0ffeae8e38d7fd30cf6', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\SmartAutoUploadImages\Vendor_Prefixed\Composer\Autoload\ComposerStaticInitdfbdffb07027e0ffeae8e38d7fd30cf6::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        return $loader;
    }
}
