<?php

// autoload_static.php @generated by Composer

namespace SmartAutoUploadImages\Vendor_Prefixed\Composer\Autoload;

class ComposerStaticInitdfbdffb07027e0ffeae8e38d7fd30cf6
{
    public static $prefixLengthsPsr4 = array (
        'S' =>
        array (
            'SmartAutoUploadImages\\Vendor_Prefixed\\Psr\\Container\\' => 52,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'SmartAutoUploadImages\\Vendor_Prefixed\\Psr\\Container\\' =>
        array (
            0 => __DIR__ . '/..' . '/psr/container/src',
        ),
    );

    public static $classMap = array (
        'SmartAutoUploadImages\\Vendor_Prefixed\\Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'SmartAutoUploadImages\\Vendor_Prefixed\\Psr\\Container\\ContainerExceptionInterface' => __DIR__ . '/..' . '/psr/container/src/ContainerExceptionInterface.php',
        'SmartAutoUploadImages\\Vendor_Prefixed\\Psr\\Container\\ContainerInterface' => __DIR__ . '/..' . '/psr/container/src/ContainerInterface.php',
        'SmartAutoUploadImages\\Vendor_Prefixed\\Psr\\Container\\NotFoundExceptionInterface' => __DIR__ . '/..' . '/psr/container/src/NotFoundExceptionInterface.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitdfbdffb07027e0ffeae8e38d7fd30cf6::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitdfbdffb07027e0ffeae8e38d7fd30cf6::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitdfbdffb07027e0ffeae8e38d7fd30cf6::$classMap;

        }, null, ClassLoader::class);
    }
}
